import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Çanakkale Villa Projesi | Erkanoğlu",
  description: "Çanakkale'de villa ve müstakil ev projeleri için mimari tasarım, mühendislik ve ruhsat çözümleri.",
};

export default function CanakkaleVillaPage() {
  return <main className="min-h-screen bg-[#f4f2ed] text-[#171717]"><header className="border-b border-black/10"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><Link href="/" className="text-xl font-semibold tracking-[0.2em]">ERKANOĞLU</Link><Link href="/evimi-hesapla" className="rounded-full bg-black px-5 py-3 text-sm text-white">Maliyeti Hesapla →</Link></div></header><section className="mx-auto max-w-5xl px-6 py-24 lg:px-10 lg:py-32"><p className="text-xs uppercase tracking-[0.3em] text-black/40">Çanakkale Villa Projesi</p><h1 className="mt-6 text-5xl font-medium leading-[0.95] tracking-[-0.05em] md:text-8xl">Hayalinizdeki<br /><span className="text-black/35">villayı tasarlayın.</span></h1><p className="mt-10 max-w-3xl text-xl leading-8 text-black/55">Arsanın koşullarını, yaşam alışkanlıklarınızı ve bütçenizi birlikte değerlendirerek villa projesini fikir aşamasından ruhsat ve uygulamaya taşıyoruz.</p><div className="mt-14 grid gap-6 md:grid-cols-2"><div className="bg-white p-7"><h2 className="text-2xl font-medium">Önce fizibilite</h2><p className="mt-3 leading-7 text-black/55">Yaklaşık yapı alanı ve yapı seviyesine göre ilk maliyet aralığını görün.</p><Link href="/evimi-hesapla" className="mt-6 inline-flex border-b border-black pb-2 text-sm">Evimi Hesapla →</Link></div><div className="bg-white p-7"><h2 className="text-2xl font-medium">Sonra proje</h2><p className="mt-3 leading-7 text-black/55">Arsanız ve beklentiniz için proje talebi bırakın.</p><Link href="/proje-talebi?projectType=Villa%20%2F%20Müstakil%20Ev" className="mt-6 inline-flex border-b border-black pb-2 text-sm">Villa Projesi Talebi →</Link></div></div><div className="mt-16 bg-[#171717] p-8 text-white md:p-12"><h2 className="text-3xl font-medium md:text-5xl">Arsanız var mı?</h2><p className="mt-5 max-w-xl text-white/55">Birkaç bilgi bırakın; projenizin ilk adımını birlikte atalım.</p><Link href="/proje-talebi?projectType=Villa%20%2F%20Müstakil%20Ev" className="mt-8 inline-flex rounded-full bg-white px-7 py-4 text-sm font-medium text-black">Villa Projesi İçin Teklif Al →</Link></div></section></main>;
}
