"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Quote = { id:number; quoteNo:string; quoteDate:string; validUntil:string|null; scope:string; description:string|null; subtotal:number; vatRate:number; total:number; currency:string; status:string };
const statuses=[{value:"TASLAK",label:"Taslak"},{value:"HAZIRLANIYOR",label:"Hazırlanıyor"},{value:"GONDERILDI",label:"Gönderildi"},{value:"KABUL_EDILDI",label:"Kabul edildi"},{value:"REDDEDILDI",label:"Reddedildi"}];
const currencies=[{value:"TRY",label:"₺ Türk Lirası"},{value:"EUR",label:"€ Euro"},{value:"USD",label:"$ ABD Doları"}];
const money=(cents:number,currency:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency,maximumFractionDigits:2}).format(cents/100);
const inputDate=(date:Date)=>{const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};

export default function Quotes({projectId}:{projectId:number}){
 const [quotes,setQuotes]=useState<Quote[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [scope,setScope]=useState(""); const [description,setDescription]=useState(""); const [subtotal,setSubtotal]=useState(""); const [vatRate,setVatRate]=useState("20"); const [currency,setCurrency]=useState("TRY"); const [status,setStatus]=useState("TASLAK"); const [quoteDate,setQuoteDate]=useState(inputDate(new Date())); const [validUntil,setValidUntil]=useState("");
 const total=useMemo(()=>{const value=Number(subtotal);const vat=Number(vatRate);return Number.isFinite(value)&&value>=0&&Number.isFinite(vat)?value*(1+vat/100):0},[subtotal,vatRate]);
 async function load(){try{setLoading(true);setError("");const response=await fetch(`/api/projects/${projectId}/quotes`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.message||"Teklifler alınamadı.");setQuotes(result.data||[]);}catch(err){setError(err instanceof Error?err.message:"Teklifler alınamadı.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[projectId]);
 async function submit(event:FormEvent){event.preventDefault();if(saving)return;try{setSaving(true);setError("");const response=await fetch(`/api/projects/${projectId}/quotes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scope,description,subtotal:Number(subtotal),vatRate:Number(vatRate),currency,status,quoteDate,validUntil})});const result=await response.json();if(!response.ok)throw new Error(result.message||"Teklif oluşturulamadı.");setQuotes(current=>[result.data,...current]);setScope("");setDescription("");setSubtotal("");setStatus("TASLAK");setValidUntil("");}catch(err){setError(err instanceof Error?err.message:"Teklif oluşturulamadı.");}finally{setSaving(false);}}
 return <section className="mt-7 border border-neutral-300 bg-[#faf9f6] p-7"><div className="flex items-end justify-between gap-6 border-b border-neutral-200 pb-5"><div><p className="text-[9px] uppercase tracking-[0.2em] text-neutral-500">Teklif Yönetimi</p><p className="mt-2 text-sm text-neutral-600">Projeye ait teklifleri oluşturun ve takip edin.</p></div><p className="text-[9px] uppercase tracking-[0.2em] text-neutral-400">{quotes.length} TEKLİF</p></div>
 <form onSubmit={submit} className="mt-5 border border-neutral-200 bg-[#f5f2eb] p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="HİZMET KAPSAMI"><input required value={scope} onChange={e=>setScope(e.target.value)} placeholder="Örn. Ruhsat proje paketi" className="field"/></Field><Field label="DURUM"><select value={status} onChange={e=>setStatus(e.target.value)} className="field">{statuses.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field><Field label="TEKLİF TARİHİ"><input type="datetime-local" value={quoteDate} onChange={e=>setQuoteDate(e.target.value)} className="field"/></Field><Field label="GEÇERLİLİK TARİHİ"><input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)} className="field"/></Field><Field label="ARA TOPLAM"><input required type="number" min="0" step="0.01" value={subtotal} onChange={e=>setSubtotal(e.target.value)} placeholder="0,00" className="field"/></Field><Field label="KDV"><div className="flex gap-2"><input type="number" min="0" max="100" value={vatRate} onChange={e=>setVatRate(e.target.value)} className="field flex-1"/><span className="flex items-center px-2 text-sm text-neutral-500">%</span></div></Field><Field label="PARA BİRİMİ"><select value={currency} onChange={e=>setCurrency(e.target.value)} className="field">{currencies.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field><div className="flex items-end justify-between border-t border-neutral-200 pt-3 md:border-0 md:pt-0"><div><p className="text-[9px] uppercase tracking-[0.15em] text-neutral-500">GENEL TOPLAM</p><p className="mt-2 text-xl">{money(Math.round(total*100),currency)}</p></div><button disabled={saving||!scope||!subtotal} className="border border-black bg-black px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-white disabled:opacity-40">{saving?"KAYDEDİLİYOR...":"TEKLİF OLUŞTUR"}</button></div></div><div className="mt-4"><Field label="AÇIKLAMA"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Teklif hakkında açıklama..." className="field resize-none"/></Field></div>{error&&<p className="mt-4 text-xs text-red-700">{error}</p>}</form>
 <div className="mt-6">{loading?<p className="text-sm text-neutral-400">Teklifler yükleniyor...</p>:quotes.length===0?<p className="text-sm text-neutral-400">Henüz teklif oluşturulmamış.</p>:<div className="space-y-3">{quotes.map(q=><div key={q.id} className="border border-neutral-200 px-5 py-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-3"><span className="text-sm font-medium">{q.quoteNo}</span><span className="text-[9px] uppercase tracking-[0.12em] text-neutral-500">{statuses.find(s=>s.value===q.status)?.label||q.status}</span></div><p className="mt-2 text-sm text-neutral-700">{q.scope}</p>{q.description&&<p className="mt-1 text-xs leading-5 text-neutral-500">{q.description}</p>}</div><div className="text-left md:text-right"><p className="text-lg">{money(q.total,q.currency)}</p><p className="mt-1 text-[10px] text-neutral-400">{new Date(q.quoteDate).toLocaleDateString("tr-TR")}{q.validUntil?` · Geçerli: ${new Date(q.validUntil).toLocaleDateString("tr-TR")}`:""}</p></div></div></div>)}</div>}</div>
 </section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[9px] uppercase tracking-[0.15em] text-neutral-500">{label}</span>{children}</label>}
