export type PlanPoint={xM:number;yM:number};
export type PlanElement={type?:string;xM:number;yM:number;widthM?:number;depthM?:number;label?:string};
export type FloorPlanRoom={name:string;xM:number;yM:number;widthM:number;depthM:number;areaM2?:number|null};
export type FloorPlan={widthM:number;depthM:number;orientation?:string;sitePolygon?:PlanPoint[];buildingPolygon?:PlanPoint[];rooms:FloorPlanRoom[];doors?:PlanElement[];windows?:PlanElement[];furniture?:PlanElement[];notes?:string[]};
const num=(v:unknown,f=0)=>typeof v==='number'&&Number.isFinite(v)?v:f;
const poly=(pts:PlanPoint[],s:number,pad:number)=>pts.map(p=>`${pad+num(p.xM)*s},${pad+num(p.yM)*s}`).join(' ');
export default function AIPlanPreview({plan,title='Parsel üzerinde mimari ön tasarım'}:{plan?:FloorPlan|null;title?:string}){if(!plan)return null;const w=Math.max(8,num(plan.widthM,20)),d=Math.max(8,num(plan.depthM,12)),s=Math.min(760/w,520/d),pad=52,sw=w*s+pad*2,sh=d*s+pad*2;const site=Array.isArray(plan.sitePolygon)&&plan.sitePolygon.length>=3?plan.sitePolygon:undefined;const building=Array.isArray(plan.buildingPolygon)&&plan.buildingPolygon.length>=3?plan.buildingPolygon:undefined;return <div className="mt-7 border-t border-black/10 pt-6"><div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-semibold tracking-[0.18em] text-black/40">MİMARİ ÖN TASARIM</p><h3 className="mt-2 text-xl font-light">{title}</h3></div><p className="text-[10px] text-black/40">{w.toFixed(1)} × {d.toFixed(1)} m · {plan.orientation||'Kuzey üstte'}</p></div><div className="mt-4 overflow-auto border border-black/15 bg-[#f8f7f2] p-3"><svg viewBox={`0 0 ${sw} ${sh}`} className="min-w-[720px] w-full" role="img" aria-label={title}>
{site?<polygon points={poly(site,s,pad)} fill="white" stroke="black" strokeWidth="3" strokeDasharray="10 7"/>:<rect x={pad} y={pad} width={w*s} height={d*s} fill="white" stroke="black" strokeWidth="2" strokeDasharray="10 7"/>}
{building?<polygon points={poly(building,s,pad)} fill="#fafafa" stroke="black" strokeWidth="4"/>:<rect x={pad} y={pad} width={w*s} height={d*s} fill="white" stroke="black" strokeWidth="3"/>}
{(plan.rooms||[]).map((r,i)=>{const x=pad+num(r.xM)*s,y=pad+num(r.yM)*s,rw=Math.max(1,Math.min(num(r.widthM,1),w-num(r.xM)))*s,rh=Math.max(1,Math.min(num(r.depthM,1),d-num(r.yM)))*s;return <g key={`r-${i}`}><rect x={x} y={y} width={rw} height={rh} fill="white" stroke="black" strokeWidth="1.5"/><text x={x+rw/2} y={y+rh/2-4} textAnchor="middle" dominantBaseline="middle" fontSize={Math.max(8,Math.min(14,Math.min(rw,rh)/6))}>{r.name.length>25?`${r.name.slice(0,24)}…`:r.name}</text>{r.areaM2!=null&&<text x={x+rw/2} y={y+rh/2+12} textAnchor="middle" fontSize="8" fill="#555">{Number(r.areaM2).toFixed(0)} m²</text>}</g>})}
{(plan.windows||[]).map((e,i)=>{const x=pad+num(e.xM)*s,y=pad+num(e.yM)*s,rw=Math.max(.5,num(e.widthM,.9))*s,rh=Math.max(.12,num(e.depthM,.15))*s;return <rect key={`win-${i}`} x={x} y={y} width={rw} height={rh} fill="white" stroke="black" strokeWidth="2"/>})}
{(plan.doors||[]).map((e,i)=>{const x=pad+num(e.xM)*s,y=pad+num(e.yM)*s,rw=Math.max(.7,num(e.widthM,.9))*s;return <g key={`door-${i}`}><line x1={x} y1={y} x2={x+rw} y2={y} stroke="white" strokeWidth="5"/><path d={`M ${x} ${y+rw} A ${rw} ${rw} 0 0 1 ${x+rw} ${y}`} fill="none" stroke="#555" strokeWidth="1"/></g>})}
{(plan.furniture||[]).map((e,i)=>{const x=pad+num(e.xM)*s,y=pad+num(e.yM)*s,rw=Math.max(.35,num(e.widthM,.8))*s,rh=Math.max(.25,num(e.depthM,.6))*s;return <g key={`f-${i}`}><rect x={x} y={y} width={rw} height={rh} fill="none" stroke="#777" strokeWidth="1"/><text x={x+rw/2} y={y+rh/2} textAnchor="middle" dominantBaseline="middle" fontSize="7" fill="#666">{e.label||e.type||''}</text></g>})}
<text x={pad+w*s/2} y="28" textAnchor="middle" fontSize="13">KUZEY ↑</text><text x={pad+w*s/2} y={sh-14} textAnchor="middle" fontSize="10" fill="#666">Parsel sınırı · yapı oturumu · şematik kat planı</text></svg></div>{plan.notes?.length?<div className="mt-4 space-y-1 text-xs leading-5 text-black/45">{plan.notes.map((n,i)=><p key={i}>· {n}</p>)}</div>:null}</div>}
