import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";

type RouteContext = { params: Promise<{ id: string }> };
type ParcelData = { parcelAreaM2:string; emsal:string; taks:string; kaks:string; floors:string; frontageM:string; depthM:string; buildingSetbackFrontM:string; buildingSetbackSideM:string; buildingSetbackRearM:string; roadWidthM:string; zoningPlan:string; notes:string };
const allowedKeys:(keyof ParcelData)[]=["parcelAreaM2","emsal","taks","kaks","floors","frontageM","depthM","buildingSetbackFrontM","buildingSetbackSideM","buildingSetbackRearM","roadWidthM","zoningPlan","notes"];
function normalizeParcelData(value:unknown):ParcelData{const s=value&&typeof value==='object'?value as Record<string,unknown>:{};return allowedKeys.reduce((o,k)=>{o[k]=typeof s[k]==='string'?s[k].trim():'';return o},{ } as ParcelData)}
function extractResponseText(payload:unknown){const d=payload as {output_text?:unknown;output?:unknown};if(typeof d.output_text==='string')return d.output_text;const chunks:string[]=[];for(const item of Array.isArray(d.output)?d.output:[]){const content=item&&typeof item==='object'?(item as {content?:unknown}).content:undefined;for(const part of Array.isArray(content)?content:[]){if(part&&typeof part==='object'&&typeof (part as {text?:unknown}).text==='string')chunks.push((part as {text:string}).text)}}return chunks.join('\n')}
function buildFallbackPlan(record:{buildingType:string;approximateArea:string|null;description:string|null},parcel:ParcelData,program:any[]){const w=Math.max(8,Number(parcel.frontageM)||12),d=Math.max(8,Math.min(24,Number(parcel.depthM)||Math.max(9,w*0.75)));let names=(Array.isArray(program)?program:[]).map(x=>typeof x?.name==='string'?x.name:'').filter(Boolean);if(!names.length){const t=(record.buildingType+' '+(record.description||'')).toLowerCase();if(t.includes('villa')||t.includes('müstakil'))names=['Giriş Holü','Salon','Mutfak','Ebeveyn Yatak Odası','Yatak Odası 2','Yatak Odası 3','Banyo','WC','Merdiven / Dolaşım'];else if(t.includes('ticari')||t.includes('dükkan'))names=['Giriş','Ana Kullanım Alanı','Ofis','Depo','WC','Teknik Hacim'];else names=['Giriş Holü','Salon','Mutfak','Yatak Odası 1','Yatak Odası 2','Banyo','WC','Dolaşım'];}names=[...new Set(names)].slice(0,10);const cols=w>=16?3:2,rows=Math.ceil(names.length/cols),cw=w/cols,ch=d/rows;return{widthM:w,depthM:d,orientation:'Kuzey üstte',rooms:names.map((name,i)=>({name,xM:(i%cols)*cw,yM:Math.floor(i/cols)*ch,widthM:cw,depthM:ch,areaM2:Math.round(cw*ch*10)/10})),notes:['AI çıktısı eksik olsa bile iç çalışma için otomatik şematik yerleşim üretildi.','Bu şema kapı, pencere, taşıyıcı, merdiven ve mevzuat kontrolleri yapılmadan uygulanamaz.']}}

export async function GET(_request:Request,{params}:RouteContext){const id=Number((await params).id);if(!Number.isInteger(id))return NextResponse.json({success:false,message:'Geçersiz proje talebi numarası.'},{status:400});const data=await prisma.projectRequest.findUnique({where:{id},select:{id:true,fullName:true,buildingType:true,projectStage:true,approximateArea:true,interestAreas:true,description:true,parcelData:true,aiDraft:true}});if(!data)return NextResponse.json({success:false,message:'Proje talebi bulunamadı.'},{status:404});return NextResponse.json({success:true,data})}
export async function PATCH(request:Request,{params}:RouteContext){try{const id=Number((await params).id),body=await request.json(),parcelData=normalizeParcelData(body.parcelData);const updated=await prisma.projectRequest.update({where:{id},data:{parcelData},select:{id:true,parcelData:true,aiDraft:true}});return NextResponse.json({success:true,data:updated})}catch(error){console.error('Parcel data PATCH error:',error);return NextResponse.json({success:false,message:'Parsel bilgileri kaydedilemedi.'},{status:500})}}
export async function POST(request:Request,{params}:RouteContext){try{const id=Number((await params).id),body=await request.json().catch(()=>({})),incoming=normalizeParcelData(body.parcelData),record=await prisma.projectRequest.findUnique({where:{id},select:{buildingType:true,projectStage:true,approximateArea:true,interestAreas:true,description:true}});if(!record)return NextResponse.json({success:false,message:'Proje talebi bulunamadı.'},{status:404});if(['parcelAreaM2','emsal','taks','floors'].some(k=>!incoming[k as keyof ParcelData]))return NextResponse.json({success:false,message:'En az parsel alanı, emsal, TAKS ve kat adedi girilmelidir.'},{status:400});await prisma.projectRequest.update({where:{id},data:{parcelData:incoming}});const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return NextResponse.json({success:false,message:'OPENAI_API_KEY tanımlı değil.'},{status:503});const model=process.env.OPENAI_PROJECT_MODEL||'gpt-5.6-luna';const system=`Sen Erkanoğlu Mimarlık & Mühendislik ekibinin iç kullanım mimari ön proje asistanısın. Yalnızca JSON üret. Amaç rapor değil, profesyonelin üzerinde çalışacağı mimari ön proje taslağıdır.
Şu JSON yapısını eksiksiz üret: {"summary":string,"feasibility":"UYGUN GÖRÜNÜYOR"|"İNCELENMELİ"|"VERİ YETERSİZ","calculations":{"theoreticalEmsalAreaM2":number|null,"theoreticalTaksFootprintM2":number|null,"notes":string[]},"program":[{"name":string,"count":number|null,"areaM2":number|null}],"layoutAlternatives":[{"title":string,"description":string}],"floorPlan":{"widthM":number,"depthM":number,"orientation":string,"rooms":[{"name":string,"xM":number,"yM":number,"widthM":number,"depthM":number,"areaM2":number|null}],"notes":string[]},"risks":string[],"professionalChecks":string[],"clientDeliverable":string[]}. floorPlan ZORUNLUDUR. Odalar bina sınırları içinde, çakışmadan ve yaklaşık gerçek ilişkilerle yerleşsin. xM/yM sol üstten metre. Bilgi eksikse makul varsayımlar yap; yine de floorPlan oluştur. Kesin ruhsat/imar uygunluğu iddiası yapma.`;const user={customerRequest:record,parcel:incoming};const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model,input:`${system}\nVERİ:${JSON.stringify(user)}`})});const payload=await response.json();if(!response.ok)return NextResponse.json({success:false,message:'AI ön proje üretimi başarısız oldu.'},{status:502});const raw=extractResponseText(payload).trim();let aiDraft:any;try{aiDraft=JSON.parse(raw.replace(/^```json\s*/i,'').replace(/\s*```$/i,''))}catch{return NextResponse.json({success:false,message:'AI beklenen JSON formatında sonuç üretmedi.'},{status:502})}if(!Array.isArray(aiDraft.program)||!aiDraft.program.length)aiDraft.program=[{name:'Giriş Holü',count:1,areaM2:8},{name:'Salon',count:1,areaM2:25},{name:'Mutfak',count:1,areaM2:12},{name:'Yatak Odası 1',count:1,areaM2:14},{name:'Yatak Odası 2',count:1,areaM2:11},{name:'Banyo',count:1,areaM2:5},{name:'WC',count:1,areaM2:2.5}];if(!aiDraft.floorPlan||!Array.isArray(aiDraft.floorPlan.rooms)||!aiDraft.floorPlan.rooms.length)aiDraft.floorPlan=buildFallbackPlan(record,incoming,aiDraft.program);const updated=await prisma.projectRequest.update({where:{id},data:{aiDraft:aiDraft as Prisma.InputJsonValue},select:{id:true,parcelData:true,aiDraft:true}});return NextResponse.json({success:true,data:updated})}catch(error){console.error('AI project draft error:',error);return NextResponse.json({success:false,message:'AI ön proje oluşturulurken hata oluştu.'},{status:500})}}
